[versions]

#插件
agp = "8.1.3"
org-jetbrains-kotlin-android = "1.8.10"

#
appcompat = "1.6.1"
core-ktx = "1.12.0"
activity-ktx = "1.8.1"
fragment-ktx = "1.6.2"

constraintlayout = "2.1.4"

material = "1.10.0"
recyclerview = "1.3.0"
viewpager2 = "1.0.0"



[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity-ktx" }
fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment-ktx" }

constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

material = { group = "com.google.android.material", name = "material", version.ref = "material" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }



[plugins]

com-android-application = { id = "com.android.application", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }



[bundles]

ktx-bundles = ["core-ktx", "activity-ktx", "fragment-ktx"]

ui-bundles = ["constraintlayout", "material", "recyclerview", "viewpager2"]

